name: Lint and Test on Pull Request

on:
  pull_request:
    branches:
      - main # Specify the branch you want to trigger this action on

jobs:
  commit-checks:
    runs-on: ubuntu-latest
    name: Checks before commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)" 
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Run lint
        run: yarn lint --quiet
      - name: Run Tests
        run: yarn test
      - name: Check for changes
        run: git diff --exit-code
      - name: Comment on PR if lint fails
        if: ${{ failure() }}
        run: |
          echo "Lint checks failed. Please review and fix the issues."
          exit 1
